export const educationData = [
  {
    degree: "Bachelor's degree",
    field: 'Computer Science',
    institution: 'National College Of Computer Studies',
    location: 'Kathmandu',
    startDate: '01/2019',
    endDate: '',
    endYear: '2019',
    gpa: 'GPA:',
  },
  {
    degree: 'Higher Secondary (+2)',
    field: 'Science',
    institution: 'Capitol Hill College',
    location: 'Kathmandu',
    startDate: '01/2014',
    endDate: '',
    endYear: '2014',
    gpa: 'GPA:',
  },
  {
    degree: 'School',
    field: 'Secondary Education',
    institution: 'Saraswoti Boarding Higher Secondary School',
    location: 'Kathmandu',
    startDate: '',
    endDate: '',
    endYear: '2012',
    gpa: 'GPA:',
  },
];
